# Pandas 실습

### 1. 실습 데이터 준비

- '서울시 지하철호선별 역별 승하차인원'

In [1]:
import warnings
warnings.filterwarnings(action='ignore')

import pandas as pd
import numpy as np

In [3]:
# 데이터 로드
df = pd.read_csv('data/CARD_SUBWAY_MONTH_202605.csv')

In [5]:
# 데이터 로드
df = pd.read_csv('data/CARD_SUBWAY_MONTH_202605.csv', index_col=False)

In [6]:
df.head()

       사용일자  노선명   역명  승차총승객수  하차총승객수      등록일자
0  20260501  5호선   방이    5527    5357  20260504
1  20260501  5호선  둔촌동   10441    9979  20260504
2  20260501  5호선  상일동   10541    9932  20260504
3  20260501  5호선   고덕    7456    7257  20260504
4  20260501  5호선   명일    6377    6251  20260504

### 2. 데이터 탐색

In [9]:
# 상위 5개의 데이터를 조회
df.head()

       사용일자  노선명   역명  승차총승객수  하차총승객수      등록일자
0  20260501  5호선   방이    5527    5357  20260504
1  20260501  5호선  둔촌동   10441    9979  20260504
2  20260501  5호선  상일동   10541    9932  20260504
3  20260501  5호선   고덕    7456    7257  20260504
4  20260501  5호선   명일    6377    6251  20260504

In [10]:
# 데이터프레임의 형태를 확인
df.shape

(19131, 6)

In [11]:
# 하위 데이터 10개를 조회
df.tail(10)

           사용일자  노선명                역명  승차총승객수  하차총승객수      등록일자
19121  20260531  8호선                문정    7350    7431  20260603
19122  20260531  8호선                장지   10401    9980  20260603
19123  20260531  8호선                복정    5988    5340  20260603
19124  20260531  8호선                산성    3611    3915  20260603
19125  20260531  8호선  남한산성입구(성남법원.검찰청)    6905    6413  20260603
19126  20260531  8호선             단대오거리    6782    6559  20260603
19127  20260531  8호선                신흥    3732    3895  20260603
19128  20260531  8호선                수진    4223    3812  20260603
19129  20260531  8호선                모란    3406    2806  20260603
19130  20260531  8호선               남위례    4515    4530  20260603

In [12]:
# 데이터의 사분위수, 표준편차, 분산 등 통계지표를 조회
df.describe()

               사용일자         승차총승객수         하차총승객수          등록일자
count  1.913100e+04   19131.000000   19131.000000  1.913100e+04
mean   2.026052e+07   11811.350740   11759.563640  2.026053e+07
std    8.944833e+00   11836.994181   12011.261965  2.614125e+01
min    2.026050e+07       1.000000       0.000000  2.026050e+07
25%    2.026051e+07    4125.000000    4022.000000  2.026051e+07
50%    2.026052e+07    8396.000000    8135.000000  2.026052e+07
75%    2.026052e+07   15701.500000   15507.500000  2.026053e+07
max    2.026053e+07  101927.000000  115875.000000  2.026060e+07

In [13]:
# 데이터의 데이터타입, 데이터갯수 등을 조회
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19131 entries, 0 to 19130
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사용일자    19131 non-null  int64
 1   노선명     19131 non-null  object
 2   역명      19131 non-null  object
 3   승차총승객수  19131 non-null  int64
 4   하차총승객수  19131 non-null  int64
 5   등록일자    19131 non-null  int64
dtypes: int64(4), object(2)
memory usage: 896.9+ KB

In [16]:
# '노선명' 컬럼이 가지고 있는 데이터의 종류를 확인, 중복되지 않은 데이터 갯수와 데이터 확인
df['노선명'].nunique()  # 27
df['노선명'].unique()  # array(['5호선', '4호선', '경의선', ...

array(['5호선', '4호선', '경의선', '3호선', '2호선', '1호선', '경인선', '경춘선', '공항철도 1호선',
       '안산선', '과천선', '분당선', '서해선', '수인선', '신림선', '우이신설선', '일산선', '장항선',
       '중앙선', '경원선', '경부선', '경강선', '9호선2~3단계', '9호선', '8호선', '7호선', '6호선'],
      dtype=object)

In [ ]:
# '역명' 컬럼이 가지고 있는 데이터의 종류를 확인, 중복되지 않은 데이터 갯수와 데이터 확인
df['역명'].nunique()  # 528
df['역명'].unique()  # array(['방이', '둔촌동', '상일동', '고덕', ...

In [ ]:
# '범주형' - value_counts() : 몇번이나 반복(등장)하는가 확인
# '노선명' 컬럼이 가지고 있는 데이터 분포 확인
df['노선명'].value_counts()

### 3. 정렬

In [26]:
# '승차총승객수' 기준으로 데이터 정렬(오름차순)
df.sort_values(by=['승차총승객수'], ascending=True)

           사용일자  노선명        역명  승차총승객수  하차총승객수      등록일자
4743   20260508  경의선        운천       1       4  20260511
2664   20260505  경의선        검암       1       0  20260508
16688  20260528  6호선       연신내       1       0  20260531
7611   20260513  6호선        신내       1       0  20260516
11070  20260518  일산선        지축       1       0  20260521
...         ...  ...       ...     ...     ...       ...
13541  20260522  1호선       서울역   97514   98036  20260525
8674   20260515  2호선        강남   98157   96835  20260518
682    20260502  2호선      홍대입구  100394  111108  20260505
8668   20260515  2호선  잠실(송파구청)  100436   98646  20260518
118    20260501  2호선      홍대입구  101927  115875  20260504

[19131 rows x 6 columns]

In [ ]:
# '승차총승객수' 기준으로 데이터 정렬(내림차순)
df.sort_values(by=['승차총승객수'], ascending=False)

In [28]:
# '승차총승객수' 기준으로 데이터 정렬(내림차순), 상위 10개 조회
df.sort_values(by=['승차총승객수'], ascending=False).head(10)

           사용일자  노선명        역명  승차총승객수  하차총승객수      등록일자
118    20260501  2호선      홍대입구  101927  115875  20260504
8668   20260515  2호선  잠실(송파구청)  100436   98646  20260518
682    20260502  2호선      홍대입구  100394  111108  20260505
8674   20260515  2호선        강남   98157   96835  20260518
13541  20260522  1호선       서울역   97514   98036  20260525
4342   20260508  2호선  잠실(송파구청)   97402   98062  20260511
17330  20260529  2호선        강남   96864   95651  20260601
13571  20260522  2호선        강남   96755   95209  20260525
4336   20260508  2호선        강남   96539   95218  20260511
8643   20260515  1호선       서울역   96164   95369  20260518

In [31]:
# '하차총승객수' 기준으로 데이터 정렬(내림차순), 상위 10개 조회(슬라이싱)
df.sort_values(['하차총승객수'], ascending=False)[0:10]

           사용일자  노선명        역명  승차총승객수  하차총승객수      등록일자
118    20260501  2호선      홍대입구  101927  115875  20260504
682    20260502  2호선      홍대입구  100394  111108  20260505
9497   20260516  2호선      홍대입구   93826  105809  20260519
14108  20260523  2호선      홍대입구   93902  105501  20260526
1898   20260504  2호선      홍대입구   91747  101530  20260507
18406  20260530  2호선      홍대입구   90426  101159  20260602
5217   20260509  2호선      홍대입구   88321   99335  20260512
8668   20260515  2호선  잠실(송파구청)  100436   98646  20260518
4342   20260508  2호선  잠실(송파구청)   97402   98062  20260511
13541  20260522  1호선       서울역   97514   98036  20260525

### 4. 선택

In [ ]:
# '사용일자' 컬럼을 인덱스로 지정하여 df2 객체를 생성
df2 = df.set_index('사용일자')
df2

In [ ]:
print(df.head(3))
print('-'*100)
print(df2.head(3))

In [37]:
# 인덱스 검색 : loc, iloc
df2.iloc[1]

노선명            5호선
역명             둔촌동
승차총승객수       10441
하차총승객수        9979
등록일자      20260504
Name: 20260501, dtype: object

In [38]:
# 20260510 일자 데이터 검색
df2.loc[20260510]

          노선명    역명  승차총승객수  하차총승객수      등록일자
사용일자
20260510  7호선  태릉입구    6549    6519  20260513
20260510  5호선    신길    3197    3374  20260513
20260510  9호선  양천향교    5221    5473  20260513
20260510  9호선    가양   13415   13294  20260513
20260510  9호선    증미    3114    3300  20260513
...       ...   ...     ...     ...       ...
20260510  중앙선    양평    3155    2873  20260513
20260510  중앙선    원덕     479     373  20260513
20260510  중앙선    용문    4829    4286  20260513
20260510  중앙선    지평      63      70  20260513
20260510  2호선    방배    8554    8679  20260513

[617 rows x 5 columns]

In [ ]:
# 일반 데이터 검색 : 팬시, 불린, query
# '노선명' 컬럼의 '2호선' 데이터 조회
# 불린 인덱싱 조건 : df2['노선명'] == '2호선'
df2[df2['노선명'] == '2호선']

In [44]:
# 일반 데이터 검색 : 팬시, 불린, query
# '노선명' 컬럼의 '2호선' 데이터 조회
# query 조건 : '노선명 == "2호선"'
df2.query('노선명 == "2호선"')
df2.query('노선명 == "2호선"')['노선명'].count()

np.int64(1550)

In [47]:
# '승차총승객수'이 50000명 이상인 '역명' 조회
# 불린 인덱싱 : df2['승차총승객수'] >= 50000
df2[df2['승차총승객수'] >= 50000]['역명']
df2[df2['승차총승객수'] >= 50000]['역명'].unique()

array(['고속터미널', '홍대입구', '강남', '잠실(송파구청)', '성수', '서울역', '수원', '용산',
       '서울대입구(관악구청)', '선릉', '을지로입구', '구로디지털단지', '신도림', '신림', '삼성(무역센터)',
       '역삼', '가산디지털단지', '사당', '혜화', '종각'], dtype=object)

In [50]:
# '승차총승객수'이 50000명 이상인 '역명' 조회
# 쿼리 : '승차총승객수 >= 50000'
df2.query('승차총승객수 >= 50000')
df2.query('승차총승객수 >= 50000')['역명'].unique()

array(['고속터미널', '홍대입구', '강남', '잠실(송파구청)', '성수', '서울역', '수원', '용산',
       '서울대입구(관악구청)', '선릉', '을지로입구', '구로디지털단지', '신도림', '신림', '삼성(무역센터)',
       '역삼', '가산디지털단지', '사당', '혜화', '종각'], dtype=object)

In [53]:
# '승차총승객수'이 50000명 이상이고, '역명' 이름이 '강남'인 데이터 조회
df2[(df2['승차총승객수'] >= 50000) & (df2['역명'] == '강남')]
df2[(df2['승차총승객수'] >= 50000) & (df2['역명'] == '강남')].count()

노선명       24
역명        24
승차총승객수    24
하차총승객수    24
등록일자      24
dtype: int64

In [56]:
# '승차총승객수'이 50000명 이상이고, '역명' 이름이 '강남'인 데이터 조회
df2.query('승차총승객수 >= 50000 & 역명 == "강남"')
df2.query('승차총승객수 >= 50000 & 역명 == "강남"').count()

노선명       24
역명        24
승차총승객수    24
하차총승객수    24
등록일자      24
dtype: int64

In [57]:
# '승차총승객수' 컬럼의 최대값
df['승차총승객수'].max()

101927

In [58]:
# '승차총승객수' 컬럼의 최소값
df['승차총승객수'].min()

1

In [60]:
# '승차총승객수' 컬럼의 최대값, '하차총승객수' 컬럼의 최소값을 조회
df.agg(
    {
        '승차총승객수': 'max',
        '하차총승객수': 'min'
    }
)

승차총승객수    101927
하차총승객수         0
dtype: int64

In [66]:
# '승차총승객수','하차총승객수' 컬럼의 최대값, 최소값, 평균값을 조회
df[['승차총승객수', '하차총승객수']].agg(['max', 'min' ,'mean', 'median'])

              승차총승객수        하차총승객수
max     101927.00000  115875.00000
min          1.00000       0.00000
mean     11811.35074   11759.56364
median    8396.00000    8135.00000

### 5. 삭제

In [ ]:
# 행기준으로 삭제, 0번지 행 삭제, df
df.drop(0)

In [ ]:
# 행기준으로 삭제, 3, 5, 7 번지 행 삭제, df
df.drop([3, 5, 7])

In [ ]:
# '등록일자' 컬럼 삭제
df.drop('등록일자', axis=1)

In [ ]:
# '등록일자', '역명' 컬럼 삭제
df.drop(['등록일자','역명'], axis=1)

### 6. 연산

In [79]:
# '승차총승객수' 컬럼에  10을 더하여, '승차총승객수_10' 컬럼을 추가
df['승차총승객수_10'] = df['승차총승객수'] + 10
df

           사용일자  노선명     역명  승차총승객수  하차총승객수      등록일자  승차총승객수_10
0      20260501  5호선     방이    5527    5357  20260504       5537
1      20260501  5호선    둔촌동   10441    9979  20260504      10451
2      20260501  5호선    상일동   10541    9932  20260504      10551
3      20260501  5호선     고덕    7456    7257  20260504       7466
4      20260501  5호선     명일    6377    6251  20260504       6387
...         ...  ...    ...     ...     ...       ...        ...
19126  20260531  8호선  단대오거리    6782    6559  20260603       6792
19127  20260531  8호선     신흥    3732    3895  20260603       3742
19128  20260531  8호선     수진    4223    3812  20260603       4233
19129  20260531  8호선     모란    3406    2806  20260603       3416
19130  20260531  8호선    남위례    4515    4530  20260603       4525

[19131 rows x 7 columns]

In [ ]:
# '승차총승객수' - '하차총승객수' 결과를 '승하차총승객수' 컬럼으로 생성하여 추가
df['승하차총승객수'] = df['승차총승객수'] - df['하차총승객수']
df

In [ ]:
# '승차총승객수' + '하차총승객수' 결과를 '승하차총승객수합계' 컬럼으로 생성하여 추가
df['승하차총승객수합계'] = df['승차총승객수'] + df['하차총승객수']
df

In [85]:
# '승하차총승객수'의 평균값, 중앙값
df['승하차총승객수'].mean()
df['승하차총승객수'].median()
df['승하차총승객수'].agg(['mean','median'])

mean      51.787099
median    97.000000
Name: 승하차총승객수, dtype: float64

In [92]:
# Index 재생성 후 df2에 반영, 기존 인덱스 컬럼 유지
df2.reset_index(inplace=True)

In [93]:
df2.head()

       사용일자  노선명   역명  승차총승객수  하차총승객수      등록일자
0  20260501  5호선   방이    5527    5357  20260504
1  20260501  5호선  둔촌동   10441    9979  20260504
2  20260501  5호선  상일동   10541    9932  20260504
3  20260501  5호선   고덕    7456    7257  20260504
4  20260501  5호선   명일    6377    6251  20260504

In [ ]:
# '노선명'컬럼의  '2호선' 데이터를 추출하여, df2_rail2 객체 생성
df2_rail2 = df.query('노선명 == "2호선"')
df2_rail2

In [ ]:
# '노선명'컬럼의  '2호선'이고, '역명'이 '강남'인 데이터를 추출하여, df_rail2_gn 객체 생성
df_rail2_gn = df.query('노선명 == "2호선" & 역명 == "강남"')  # 31
df_rail2_gn

In [103]:
print(df2_rail2.head())
print()
print(df_rail2_gn.head())

         사용일자  노선명         역명  승차총승객수  하차총승객수      등록일자  승차총승객수_10  승하차총승객수  \
107  20260501  2호선  용두(동대문구청)    1980    1746  20260504       1990      234
108  20260501  2호선      신정네거리    7710    7364  20260504       7720      346
109  20260501  2호선       양천구청    4845    4751  20260504       4855       94
110  20260501  2호선        도림천     814     803  20260504        824       11
111  20260501  2호선        신설동    3984    3453  20260504       3994      531

     승하차총승객수합계
107       3726
108      15074
109       9596
110       1617
111       7437

          사용일자  노선명  역명  승차총승객수  하차총승객수      등록일자  승차총승객수_10  승하차총승객수  \
134   20260501  2호선  강남   56904   56781  20260504      56914      123
698   20260502  2호선  강남   59964   58975  20260505      59974      989
1570  20260503  2호선  강남   38314   36857  20260506      38324     1457
1857  20260504  2호선  강남   84694   83040  20260507      84704     1654
2767  20260505  2호선  강남   40017   39003  20260508      40027     1014

      승하차총승객수합계
134      113685
698      118939
1570      75171
1857     167734
2767      79020

In [ ]:
# df2_rail2 데이터프레임과 df_rail2_gn 데이터프레임을 사칙연산 - 인덱스와 컬럼명이 모두 동일해야 연산이 가능!!
df2_rail2.loc[134:] + df_rail2_gn.loc[134:]

In [ ]:
# df2_rail2 데이터프레임과 df_rail2_gn 데이터프레임을 사칙연산 - Inner Join(교집합)
# pandas.merge()
pd.merge(df2_rail2, df_rail2_gn)

In [ ]:
df2_rail2.head()
df2_rail2.drop(['승차총승객수_10', '승하차총승객수합계'], axis=1, inplace=True)
df2_rail2

In [ ]:
pd.merge(df2_rail2, df_rail2_gn)

In [ ]:
# Left outer join
pd.merge(df2_rail2, df_rail2_gn, how='left').query('역명 != "강남"')

In [ ]:
# Right outer join
pd.merge(df2_rail2, df_rail2_gn, how='right')

In [120]:
# Full outer join
pd.merge(df2_rail2, df_rail2_gn, how='outer')

,사용일자,노선명,역명,승차총승객수,하차총승객수,등록일자,승하차총승객수,승차총승객수_10,승하차총승객수합계
0,20260501,2호선,강남,56904,56781,20260504,123,56914.0,113685.0
1,20260501,2호선,강변(동서울터미널),29730,33087,20260504,-3357,NaN,NaN
2,20260501,2호선,건대입구,46972,46849,20260504,123,NaN,NaN
3,20260501,2호선,교대(법원.검찰청),15381,19794,20260504,-4413,NaN,NaN
4,20260501,2호선,구로디지털단지,37858,35789,20260504,2069,NaN,NaN
...,...,...,...,...,...,...,...,...,...
1545,20260531,2호선,종합운동장,20041,22953,20260603,-2912,NaN,NaN
1546,20260531,2호선,충정로(경기대입구),4857,5292,20260603,-435,NaN,NaN
1547,20260531,2호선,한양대,3968,4535,20260603,-567,NaN,NaN
1548,20260531,2호선,합정,26927,28148,20260603,-1221,NaN,NaN
1549,20260531,2호선,홍대입구,71629,73237,20260603,-1608,NaN,NaN

### 7. 샘플링

In [139]:
# 상위 10개 데이터를 샘플링 - 임의로 10개의 데이터 추출
df_sample_10 = df.sample(n=10)
df_sample_10

,사용일자,노선명,역명,승차총승객수,하차총승객수,등록일자,승차총승객수_10,승하차총승객수,승하차총승객수합계
4117,20260507,4호선,사당,29984,25954,20260510,29994,4030,55938
15169,20260525,8호선,천호(풍납토성),12904,14338,20260528,12914,-1434,27242
12818,20260521,5호선,광화문(세종문화회관),40115,42646,20260524,40125,-2531,82761
6692,20260511,경부선,신도림,4231,4543,20260514,4241,-312,8774
8855,20260515,7호선,장암,3364,1343,20260518,3374,2021,4707
5908,20260510,경부선,송탄,4422,4715,20260513,4432,-293,9137
8353,20260514,2호선,역삼,59109,67416,20260517,59119,-8307,126525
15222,20260525,6호선,고려대(종암),5104,5172,20260528,5114,-68,10276
8777,20260515,5호선,여의도,33502,36560,20260518,33512,-3058,70062
1197,20260502,경부선,금정,21957,22003,20260505,21967,-46,43960

### 8. 그룹핑
- 범주형 데이터 확인

In [ ]:
df.info()

In [ ]:
# '사용일자', '노선명', '역명' 컬럼의 value_counts()
df[['노선명', '역명']].value_counts()

In [ ]:
# '사용일자' 기준으로 그룹핑 + 집계함수
df.groupby('사용일자').count()

In [ ]:
# '사용일자', '노선명' 기준으로 그룹핑 + 집계함수
df.groupby(['사용일자', '노선명']).count()

In [155]:
# '노선명' 기준으로 그룹핑
df.groupby('노선명')[['승차총승객수', '하차총승객수']].sum()

            승차총승객수    하차총승객수
노선명
1호선        8579012   8398352
2호선       43635653  44152080
3호선       16759009  16567597
4호선       16896742  17236548
5호선       20615400  20368096
6호선       10880977  10852030
7호선       18345468  18064097
8호선        6392620   6433172
9호선        8762390   8901704
9호선2~3단계   3546396   3538049
경강선        1117334   1077057
경부선       14896578  14730801
경원선        6749979   6512313
경의선        3527436   3451674
경인선        8473039   8267174
경춘선        1315116   1266005
공항철도 1호선   4178849   3905475
과천선        3417291   3388878
분당선       11496150  11862278
서해선         351712    378457
수인선        2051167   1994029
신림선        1477272   1438242
안산선        3831079   3809489
우이신설선      1532687   1468465
일산선        3655008   3549462
장항선         686782    652032
중앙선        2791805   2708656

### 9. 결측값(NaN) 처리

In [ ]:
df2['3호선'] = np.nan
df2

In [ ]:
df2.info()

In [163]:
# 결측값 갯수 구하기, isna(), isnull()
df2.isna().sum()

사용일자          0
노선명           0
역명            0
승차총승객수        0
하차총승객수        0
등록일자          0
3호선       19131
dtype: int64

In [165]:
# 타이타닉 데이터셋 로드
td = pd.read_csv('data/titanic/train.csv')
td.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
td.info()

In [167]:
td.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [175]:
# Age 컬럼은 평균 값으로 결측치 대체, fillna()
age_mean = td['Age'].mean()
age_mean
td['Age'] = td['Age'].fillna(age_mean)

In [176]:
td.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [179]:
# Cabin 컬럼은 삭제
td.drop('Cabin', axis=1, inplace=True)

In [180]:
td.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

In [182]:
# Embarked 값은 이전 값으로 대체
td['Embarked'] = td['Embarked'].ffill()

In [183]:
td.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64